---
- name: Uninstall Elastic GPG key
  ansible.builtin.file:
    path: /usr/share/keyrings/elastic-keyring.gpg
    state: absent

- name: Remove Elastic APT Repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/{{ metricbeat_major_version }}.x/apt stable main'
    filename: elastic
    state: absent
    update_cache: true
